### ISSUE TITLE
Button remain in status "hold"

### ISSUE THREAD

**Issue by williammanco** [sonsoleslp/react-click-n-hold#1]
Hi @sonsoleslp,
maybe a bug, when I "click and hold" and go outside of the button, this remain in status "hold"

**Comment by sonsoleslp** [comment]
Hi! It is the intended behaviour. As long as you keep holding the click, the event will not stop.

**Comment by williammanco** [comment]
@sonsoleslp sorry maybe I did not explain it well.
When keep holding the click on the button area and moving the cursor out of the button area, **now release the click**, the event not end and stay in 'hold' status, work correctly only if stay on the area button.

**this is the map of event on button area (correct)**
_click_ -> `onStart`
_keep holding click_ ->` onClickNHold`
_release click_ -> **`onEnd`**

**this is the map of event with bug, when moving the mouse pointer outside the button**
_click_ -> `onStart`
_keep holding click_ -> `onClickNHold`
_keep holding click and move cursor outside the button_ -> `onClickNHold`
_release click_ -> **`onClickNHold`**

sorry for my english

**Comment by sonsoleslp** [comment]
@williammanco  I accepted your PR. Thank you very much 🥇
